version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_SEARCH_API_KEY=your_google_search_api_key
      - GOOGLE_CSE_ID=your_google_cse_id
      - FLASK_ENV=production
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: "redis:alpine"